### ISSUE TITLE
دو مشکل اساسی در برنامه

### ISSUE THREAD

**Issue by mrmmg** [Sanaebadi97/AndroidWp#1]
`D: <-- 403 Request blocked by Privoxy http://siteurl/wp-json/wp/v2/posts?_embed`
این مشکل گویا از رتروفیت هست ، من کار نکردم و هرچه سرچ زدم به نتیجه ای نرسیدم برای رفع کردنش
مشکل از هاستمم نیست چون تست شده بارها و خروجی میده کامل
<hr>
`E: No adapter attached; skipping layout`
<br>
اینم یه ارور دیگه که گویا نتونسته ادپتر ریسایکلر ویو رو پیدا کنم
البته بنده متوجه نشدم شما چطوری ریسایکلر رو ساختی
<hr>
در ضمن هر دوی این مشکل ها به صورتی هست که برنامه کامپایل و اجرا میشه اما با یک صفحه سفید روبرو میشم
<hr>
ممنون میشم راهنمایی کنی
<br>
<b>MR.MMG</b>

**Comment by Sanaebadi97** [comment]
The Adapter Is Ok and If You Parse The Json Right .. You Should Run your code ... Plz Run My code and After That If You get any Error Tell me :)

I run Project And Without Any Error, I get Cool OutPut .. Check Your Code

**Comment by mrmmg** [comment]
> The Adapter Is Ok and If You Parse The Json Right .. You Should Run your code ... Plz Run My code and After That If You get any Error Tell me :)
> 
> I run Project And Without Any Error, I get Cool OutPut .. Check Your Code

Hello
The Retrofit problem is resolved but the app cannot find an adapter!
for more information see this [video](https://cdn.mrmmg.ir/video.html), please.

<b>Best Regards, Mr.MMG</b>

**Comment by Sanaebadi97** [comment]
Drear The problem is from you ... I run The project In Android Studio And Run .. See This [Video](http://sanaebadi.info/GitHub/TestApp.mkv)  
You Duplicate in this line too in ApiCleint.java `    .addInterceptor(httpLoggingInterceptor)` and are you sure set layout manager on recyclerView ? or set ArrayList on that? see this [link](https://stackoverflow.com/questions/29141729/recyclerview-no-adapter-attached-skipping-layout)
